name: Collect Twitch categories

on:
  schedule:                      # every 5 min (smallest allowed) :contentReference[oaicite:2]{index=2}
    - cron:  '*/5 * * * *'
  workflow_dispatch:             # allow manual run from the UI

permissions:                     # enable commit + artifacts
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 6           # stays safely within one cron window
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run 10 s polling loop (~5 min)
        run: python scripts/collector_loop.py

      - name: Upload data artifact
        uses: actions/upload-artifact@v4        # official action :contentReference[oaicite:3]{index=3}
        with:
          name: twitch-top-categories
          path: data/
          retention-days: 90                    # optional; default is 90 d :contentReference[oaicite:4]{index=4}

      # OPTIONAL: commit the new CSV back to the repo so it lives forever
      - name: Commit updated CSV
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/twitch_top_categories.csv
          git commit -m "data: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
