name: Sensor Tower DL           # Optional but nice to have
on:                             # <-- the missing key
  workflow_dispatch:            # run it manually from the Actions tab

permissions:
  contents: read                # required by actions/checkout
  id-token: write               # required for OIDC federation

jobs:
  query_bq:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
        service_account:            ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        # token_format defaults to 'access_token', leave it that way

    - name: Set up Cloud SDK + bq
      uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: bq      # pulls the BigQuery CLI into the PATH

    - name: Run a BigQuery query
      run: |
        bq query --nouse_legacy_sql \
          'SELECT 1 AS one'
